spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <clientID>
            client-secret: <clientSecret>
  cassandra:
    keyspace-name: main
    schema-action: CREATE_IF_NOT_EXISTS
    request:
      timeout: 20s
    connection:
      connect-timeout: 10s
      init-query-timeout: 20s
    local-datacenter: datacenter1

logging.level:
  org.springframework.data.cassandra.core.cql.CqlTemplate: DEBUG