spring:
  data:
    cassandra:
      keyspace-name: main
      username: <username>
      password: <password>
      schema-action: recreate-drop-unused
      request:
        timeout: 20s
      connection:
        connect-timeout: 10s
        init-query-timeout: 20s
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <clientID>
            client-secret: <clientSecret>

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: <db-id>
  region: asia-south1
  keyspace: main
  application.token: <token>
